jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8
  username: root
  password: root

server:
  port: 1122

logging:
  level:
    com.lzcong: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.lzcong.domain


